/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as erc20TokensSol from './ERC20Tokens.sol';
import type * as swapSol from './Swap.sol';

export type { erc20TokensSol };

export type { swapSol };
